version: 2.1
jobs:
    build:
        docker:
            #- image: mcr.microsoft.com/dotnet/sdk:5.0-focal
            - image: jetcipher/circleci-dotnet-core:3.0
        steps:
            - setup_remote_docker:
                docker_layer_caching: false
                version: 20.10.7
            - checkout
            #Dotnet restore
            #- run:
            #    name: "Restore"
            #    command: dotnet restore
            #    working_directory: DryPro.Inventory.Management/DryPro.Inventory.Management.UI
            #Dotnet build
            #- run:
            #    name: "Build"
            #    command: dotnet build -c Release /p:env=Test
            #    working_directory: DryPro.Inventory.Management/DryPro.Inventory.Management.UI
            - run:
                name: "Build and push Docker image"
                command: |
                    docker build -t dryproui .
                    docker tag dryproui registry.heroku.com/dryproinventory/web
                    echo $HEROKU_TOKEN | docker login --username=_ --password-stdin registry.heroku.com
                    sudo curl https://cli-assets.heroku.com/install.sh | sh
                    HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:login
                    HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:push web --app dryproinventory
                    HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:release --app dryproinventory web