version: 2.1
orbs:
  heroku: circleci/heroku@1.2.6
  windows: circleci/windows@2.4.1
jobs:
  build:
    description: Build application with Release configuration
    executor:
      name: windows/default
    steps:
      - checkout
      #Dotnet restore
      - run:
          name: "Restore"
          command: dotnet restore
          working_directory: DryPro.Inventory.Management/DryPro.Inventory.Management.UI
      #Dotnet build
      - run:
          name: "Build"
          command: dotnet build -c Release /p:env=Test
          working_directory: DryPro.Inventory.Management/DryPro.Inventory.Management.UI
workflows:
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git