version: 2.1
jobs:
build:
docker:
    - image: jetcipher/circleci-dotnet-core:2.2
steps:
    - setup_remote_docker:
    docker_layer_caching: false
    version: 20.10.11
    - checkout
#Dotnet restore
- run:
    name: Restore
    command: dotnet restore
    working_directory: DryPro.Inventory.Management.UI
#Dotnet build
- run:
    name: Build
    command: dotnet build -c Release
    working_directory: DryPro.Inventory.Management.UI
- run:
    name: Build and push Docker image
    command: |
    docker build --tag registry.heroku.com/dryproinventory/web dryproui
    echo $HEROKU_TOKEN | docker login --username=_ --password-stdin registry.heroku.com
    docker push registry.heroku.com/dryproinventory/web
    sudo curl https://cli-assets.heroku.com/install.sh | sh
    HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:login
    HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:release --app dryproinventory web